### ISSUE TITLE
Remove dependency on epoll

### ISSUE THREAD

**Issue by willi-kappler** [jonhoo/mio-pool#1]
In the file src/poll.rs "epoll" from the "nix" crate is used.
Unfortunately this means that mio-pool is currently Linux-only
It should be possible to use the platform independend "poll" from mio.

**Comment by jonhoo** [comment]
This crate used to use `poll` from `mio`, but it was removed in https://github.com/jonhoo/mio-pool/commit/97380a6cc2b5d1d930e8f0f2b068dedb807f6088 because `mio::Poll` isn't built to allow fast, concurrent polling on the same selector from multiple threads. See also https://github.com/carllerche/mio/issues/809

**Comment by willi-kappler** [comment]
Thanks for the info! It's a pitty that the performance is suffering but maybe this will be fixed in a future version of mio.

**Comment by jonhoo** [comment]
Actually, I think future version of `mio` (if not the current one too) you won't even be _able_ to access a `Poll` from different threads, because that was never an intended use-case for `mio`. It's explicitly a non-goal iirc from discussions with @carllerche back in the day.

**Comment by carllerche** [comment]
My thought is to add Poll::try_clone() -> Option<Poll>. This would allow platforms that support concurrent polling to provide the functionality.

**Comment by jonhoo** [comment]
@carllerche From memory, the issue was actually that concurrent polling through `mio` carried with it a bunch of overhead compared to just native shared `epoll`. That's what https://github.com/carllerche/mio/issues/809 was all about.

**Comment by carllerche** [comment]
@jonhoo Right, today. In the linked issue:

> At some point in the future, the strategy for concurrency will be to clone the poll handle. Though it will probably be Poll::try_clone or something like that given that there are additional complexities (like windows & iocp have a concurrency limit, and it is platform specific).
